# _config.yml

# Site settings
title: "Blog de Fikua"
description: "Información sobre las mejores prácticas de codificación, patrones de diseño, arquitectura y mucho más."
author: Oriol Canadés
baseurl: ""
url: "https://oriolcanades.github.io/blog"

# Build settings
markdown: kramdown
permalink: pretty
paginate: 5

# Theme settings
theme: minima # Change if using a custom theme

# Collections
collections:
  posts:
    output: true

# Defaults for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Oriol Canadés"

# Plugins (optional)
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Category options
gems:
  - jekyll-paginate
