@startuml
'https://plantuml.com/sequence-diagram

autonumber

participant "Holder Wallet" as wallet
participant "Credential Issuer" as issuer

activate wallet
wallet -> issuer++: POST /oauth/token\nToken Request (pre-authorized_code, tx_code)
issuer --> wallet--: Token Response (access_token, token_type, expires_in, refresh_token)

wallet -> issuer++: POST /oid4vci/v1/credential\nCredential Request (access_token, credential_request)
issuer --> wallet--: Credential Response (transaction_id)

wallet -> issuer++: POST /oid4vci/v1/deferred-credential\nDeferred Credential Request (access_token, transaction_id)
issuer --> wallet--: Invalid Access Token

wallet -> issuer++: POST /oauth/token\nToken Request (refresh_token, grant_type=refresh_token)
issuer --> wallet--: Token Response (access_token, token_type, expires_in)

wallet -> issuer++: POST /oid4vci/v1/deferred-credential\nDeferred Credential Request (access_token, transaction_id)
issuer --> wallet--: Deferred Credential Response (credentials)
deactivate wallet

@enduml
